name: Build & Release

on:
  workflow_dispatch:
    inputs:
      deploy_artifacts:
        description: 'Deploy artifacts to GitHub Maven repository? (default: false)'
        required: false
        default: false
        type: boolean
      dry_run:
        description: 'Perform a dry run for deployment (default: false)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8 (Amazon Corretto)
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Maven
      run: |
        mvn -B install

    - name: Deploy to GitHub Packages (Optional)
      if: ${{ github.event.inputs.deploy_artifacts == 'true' }}
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF
        if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
          echo "Dry run: mvn -B deploy:deploy-DrepositoryId=github -Durl=https://maven.pkg.github.com/${{ github.repository }} -DskipTests"
        else
          mvn -B deploy:deploy -DrepositoryId=github -Durl=https://maven.pkg.github.com/${{ github.repository }} -DskipTests
        fi
